### ISSUE TITLE
classloader-suffix is returning as NULL

### ISSUE THREAD

**Issue by mishterk** [dangoodman/composer-for-wordpress#5]
Howdy, 

Nice plugin — thanks for putting this together.

I noticed I can't seem to use the classloader-suffix with any success. I've tried using it both at the top level of the composer.json file and also within "extra" but neither seems to take effect. 

When I dump the output of the call to `$composerConfig->get('classloader-suffix')` in `\Dangoodman\ComposerForWordpress\ComposerForWordpress::onPostAutoloadDump()`, the value is null.

This isn't a critical issue but thought I'd raise it in case it's a bug. If I'm doing something wrong (maybe you've seen this before) please school me so I can get myself sorted :) 

I'm using Composer version 1.10.21 and haven't tried using version 2 yet. 

Cheers,
Phil

**Comment by dangoodman** [comment]
Hi Phil,

It appears that, actually, `classloader-suffix` has to be set in the `config` section of a `composer.json`. I have updated the readme.

**Comment by mishterk** [comment]
Ahhh, perfect. Thanks @dangoodman!
