### ISSUE TITLE
Issue with laminas

### ISSUE THREAD

**Issue by Androlax2** [dangoodman/composer-for-wordpress#6]
Hello,

There are a problem with 3rd party plugin, you can see there : 

https://github.com/laminas/laminas-zendframework-bridge/issues/88

instance of `Composer\Autoload\ClassLoader` is required.
But the suffix of `Autoload` is changing there.

Is there any reason to add a suffix to `Autoload` ? 

I figured out that were a `classloader-suffix` configuration to `composer.json` but when we set it to `null` we can't get rid of the suffix 
Otherwise, couldn't we get rid of this `suffix` by default ?

**Comment by Androlax2** [comment]
Did a little PR to fix that with a configuration https://github.com/dangoodman/composer-for-wordpress/pull/7

**Comment by Androlax2** [comment]
Okay, I understand more the initial problem thanks to : https://github.com/composer/composer/issues/3852

With the PR I made atleast, we could add in our `roots/bedrock` configuration part the possibility to disable the suffix of Autoload when we do not need to

**Comment by Androlax2** [comment]
Or it should replace anywhere in `vendor` directory the base `ClassLoader` with the new one with the suffix instead of `ClassLoader.php`, `autoload_real.php`, `autoload_static.php` only.

What do you think ?

**Comment by dangoodman** [comment]
Hello,

Rewriting the entire `vendor` in a way compatible with all other libs seems almost impossible due to the dynamic nature of PHP. It also feels out of the scope of the plugin.

It looks like disabling a ClassLoader suffix kind of defeats the purpose of this plugin. Maybe you don't the plugin at all? I think Bedrock solves the problem.

**Comment by Androlax2** [comment]
Hello @dangoodman,

thanks for your answer.
The problem is there : https://github.com/wp-media/imagify-plugin/issues/639

There is a plugin I installed through composer and this one load this package with the suffix on Autoloader, but it don't works properly with `laminas` as `laminas` is waiting for a `ClassLoader` type so it entirely break a WordPress website : 

`Fatal error: Uncaught TypeError: Argument 2 passed to Laminas\ZendFrameworkBridge\Autoloader::createPrependAutoloader() must be an instance of Composer\Autoload\ClassLoader`

**Comment by dangoodman** [comment]
The purpose of this plugin is to allow multiple WordPress plugins to bring their own versions of Composer without a conflict. It is required for a typical WordPress installation.

Bedrock doesn't have that problem thus doesn't require this plugin. 

I can see the following options:
– Disable this plugin with Bedrock or Composer options.
– Somehow, prepare the wp-media/imagify-plugin to be run in a Bedrock environment by removing this plugin from the `require` section.

**Comment by Androlax2** [comment]
This issue is resolved thanks to `Composer v2` where we can [allow-plugins](https://getcomposer.org/doc/06-config.md#allow-plugins) now : 

```json
"allow-plugins": {
      "dangoodman/composer-for-wordpress": false
},
```
